name: Test Cypress run with DEBUG

on:
  workflow_dispatch:

env:
  NO_COLOR: true
  DEBUG: cypress:*

jobs:
  Cypress-Test-Pure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests/cy-pure

  Cypress-Test-Warning:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: tests/cy-with-browser-sync
