name: Test Cypress run

on:
  workflow_dispatch:

env:
  NO_COLOR: true
  TERM: xterm

jobs:
  Cypress-Test-Pure:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'

      - name: Install npm dependencies
        run: npm --prefix ./tests/cy-pure ci

      - name: Cypress run
        run: npx cypress run --project ./tests/cy-pure --e2e --browser chrome

  Cypress-Test-Warning:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18 environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'

      - name: Install npm dependencies
        run: npm --prefix ./tests/cy-with-browser-sync ci

      - name: Cypress run
        run: npx cypress run --project ./tests/cy-with-browser-sync --e2e --browser chrome
